### ISSUE TITLE
Падение при добавлении судна

### ISSUE THREAD

**Issue by andmyr** [andmyr/DF#5]
java.lang.NumberFormatException: Invalid long: "33847-TJ"
	at java.lang.Long.invalidLong(Long.java:124)
	at java.lang.Long.parse(Long.java:363)
	at java.lang.Long.parseLong(Long.java:353)
	at java.lang.Long.parseLong(Long.java:321)
	at ua.od.and.df.activities.AddShipActivity.onClick(Unknown Source)
	at android.view.View.performClick(View.java:4856)
	at android.view.View$PerformClick.run(View.java:19956)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)

**Comment by andmyr** [comment]
Исправлено
